include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - web/**
  errors:
    avoid_print: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
